### ISSUE TITLE
Invalid types for nested fields

### ISSUE THREAD

**Issue by fcoelho** [twilio/twilio-node#1140]
Some of the types exported by this package aren't valid. There's a mix of variable casing and it doesn't seem like results get normalized correctly

For example in this program:

```typescript
import twilio from "twilio";

async function main() {
  const client = twilio(
    process.env.TWILIO_ACCOUNT_SID,
    process.env.TWILIO_AUTH_TOKEN
  );

  const result = await client.pricing.v2.voice.numbers
    .get(process.env.DESTINATION_NUMBER ?? "")
    .fetch();

  console.log(result);
}

main().catch(console.error);
```

```console
$ pnpm tsx index.ts
{
  destinationNumber: '+44xxxxxxx',
  originationNumber: null,
  country: 'United Kingdom',
  isoCountry: 'GB',
  outboundCallPrices: [
    {
      base_price: '0.03050',
      current_price: '0.03050',
      origination_prefixes: [Array]
    }
  ],
  inboundCallPrice: null,
  priceUnit: 'USD',
  url: 'https://pricing.twilio.com/v2/Voice/Numbers/+44xxxxxxx'
}
```

`result` is of type [`NumberInstance`](https://github.com/twilio/twilio-node/blob/7d9dd1fe9d2bc7e68f90a66e05785586ab20b270/src/rest/pricing/v2/voice/number.ts#L165) and it sets [`outboundCallPrices`](https://github.com/twilio/twilio-node/blob/7d9dd1fe9d2bc7e68f90a66e05785586ab20b270/src/rest/pricing/v2/voice/number.ts#L178) but [the actual type of that field says a property `currentPrice` should exist](https://github.com/twilio/twilio-node/blob/7d9dd1fe9d2bc7e68f90a66e05785586ab20b270/src/rest/pricing/v2/voice/number.ts#L30-L34) but it's never converted from `current_price` into `currentPrice`.

`inboundCallPrice` can also be null, but that's not reflected in the field type: https://github.com/twilio/twilio-node/blob/7d9dd1fe9d2bc7e68f90a66e05785586ab20b270/src/rest/pricing/v2/voice/number.ts#L208

The source type descriptions in the openapi spec correctly mentions that both of these are nullable: https://github.com/twilio/twilio-oai/blob/bcf1d20ba0710f272748c3d23312498e28a99315/spec/yaml/twilio_pricing_v2.yaml#L304-L341

**Comment by manisha1997** [comment]
Hello!
With the latest release, this issue is resolved.
Please upgrade to the latest release verion.

**Comment by fcoelho** [comment]
Hi @manisha1997 I don't think this was fixed. Just tested this with twilio 5.10.3 and got the exact same output as above. The type definitions for inbound/outbound prices are [still not nullable](https://github.com/twilio/twilio-node/blob/main/src/rest/pricing/v2/voice/number.ts#L207-L208) in the main branch and there have been no changes to the number.ts file either: https://github.com/twilio/twilio-node/commits/5.10.3/src/rest/pricing/v2/voice/number.ts

Have changes been made elsewhere and not reflected in this repository yet?

**Comment by veedeo** [comment]
types are still broken, any update ?

**Comment by meshelton** [comment]
Yeah, the types are still broken, I'm able to work around it using casting but that's pretty bad/not sustainable.

**Comment by dmitriy-kudelko** [comment]
Still broken in 5.12.1. We're using `lookups.v2.phoneNumbers` API, and it deviates from the specified types. Looks like all nested property keys are still returned in snake_case, while types are defined with camelCase, e.g.:

https://github.com/twilio/twilio-node/blob/b9e0b4bcd290aa96d6c9c202998ab341870208b4/src/rest/lookups/v2/phoneNumber.ts#L27-L31

Actual response:

```
  "callerName": {
    "caller_name": "...",
    "caller_type": "...",
    "error_code": null
  }
```

Can you please fix that?

**Comment by manisha1997** [comment]
We are actively working on this and plan to release in next cycle.

**Comment by manisha1997** [comment]
Hey folks!
Is this more to what you expect in the response?
```
{
  destinationNumber: '+1XXXXXXXXX',
  originationNumber: null,
  country: 'India',
  isoCountry: 'IN',
  outboundCallPrices: [
    PricingV2VoiceVoiceNumberOutboundCallPrices {
      basePrice: '0.04050',
      currentPrice: '0.04050',
      originationPrefixes: [Array]
    }
  ],
  inboundCallPrice: null,
  priceUnit: 'USD',
  url: 'https://pricing.twilio.com/v2/Voice/Numbers/+1XXXXXXX'
}
```

I am clarifying the requirements here to write a more appropriate code for the generator.

**Comment by manisha1997** [comment]
Please note the Nested class name is in the output

**Comment by veedeo** [comment]
Same shape as API response, but camelCase (without additional nested classes) it more intuitive

**Comment by manisha1997** [comment]
okay, cool.

**Comment by meshelton** [comment]
Also this doesn't work for submission of data. Here's an example of what currently works with 5.12.1:

```typescript
  const data: ContentCreateRequest = {
    friendly_name,
    language: locale,
    types: {
      'twilio/text': {
        body: templateDetails.templateBody,
      },
    } as Types,
    variables: templateDetails.variableDefaults,
  } as ContentCreateRequest;
  try {
    return await client.content.v1.contents.create(data);
  } catch (e) {
    console.error(`Failed to create template for ${notificationType}`, e);
    throw e;
  }
```

The types the library provides as `ContentCreateRequest` would be:
```typescript
  const data: ContentCreateRequest = {
    friendlyName,
    language: locale,
    types: {
      twilioText: {
        body: templateDetails.templateBody,
      },
    },
    variables: templateDetails.variableDefaults,
  };
  try {
    return await client.content.v1.contents.create(data);
  } catch (e) {
    console.error(`Failed to create template for ${notificationType}`, e);
    throw e;
  }
```
Which if used throws an error:
```json
{"code":92001,"message":"Invalid types. At least one content type definition is required","more_info":"https://www.twilio.com/docs/errors/92001","status":400}
```

**Comment by manisha1997** [comment]
okay, I will take a look there too.

**Comment by manisha1997** [comment]
@veedeo 
This is what i am doing during testing,
```
result.outboundCallPrices is now of Type Array<PricingV2VoiceVoiceNumberOutboundCallPrices>
```
the output is like 
```
{
  "destinationNumber": "+1XXXXX",
  "originationNumber": null,
  "country": "India",
  "isoCountry": "IN",
  "outboundCallPrices": [
    {
      "basePrice": "0.04050",
      "currentPrice": "0.04050",
      "originationPrefixes": [
        "ALL"
      ]
    }
  ],
  "inboundCallPrice": null,
  "priceUnit": "USD",
  "url": "https://pricing.twilio.com/v2/Voice/Numbers/+1XXXXX"
}
```

Is this the correct representation of what you are expecting?

**Comment by manisha1997** [comment]
Hey folks, I have raised the preview PR as to how the changes look like https://github.com/twilio/twilio-node/pull/1174/changes. We are open to comments if you see something is not according to your expectations.

**Comment by manisha1997** [comment]
PR merged. Will be available in the next release.

**Comment by manisha1997** [comment]
The fix is present in version 5.13.0.
