### ISSUE TITLE
Unhandled Rejection in Twilio SDK When Catching Exceptions in Application

### ISSUE THREAD

**Issue by mimu0** [twilio/twilio-node#949]
### Issue Summary
Twilio SDK has unhandled rejection in SDK and can't catch it from the application. This issue causes application termination.

### Steps to Reproduce
1. See the code snippet

### Code Snippet
```node
const client = require('twilio')(TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN);
const getMessages = async () => {
  try {
    const result =  await client.conversations.v1.services('SERVICE_SID').conversations('NOT_EXISTING_CONVERSATION_SID').messages.list();
    return result;
  } catch (e) {
    console.log('------catch from getMessages', e);
  }
};

process.on('unhandledRejection', (reason, promise) => {
  // this should not be called since we catch every exception
  console.log('------unhandledRejection', reason, promise);
});
process.on('rejectionHandled', (promise) => {
  console.log('------rejectionHandled', promise);

});

getMessages().then((messages) => {
  console.log('------messages', messages);
}).catch((e) => {
  console.log('------catch from caller', e);
});
```

### Exception/Log
```
------catch from getMessages RestException [Error]: The requested resource /Services/ISe0ef118171da46b9bd8ef1d33c82349e/Conversations/CHc8c5b974343a4546bb022e511885b6f1/Messages was not found
    at MessagePage.processResponse (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:135:19)
    at new Page (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:17:28)
    at new MessagePage (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:315:9)
    at /Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:282:63
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  code: 20404,
  moreInfo: 'https://www.twilio.com/docs/errors/20404',
  details: undefined
}
------messages undefined
------unhandledRejection RestException [Error]: The requested resource /Services/ISe0ef118171da46b9bd8ef1d33c82349e/Conversations/CHc8c5b974343a4546bb022e511885b6f1/Messages was not found
    at MessagePage.processResponse (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:135:19)
    at new Page (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:17:28)
    at new MessagePage (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:315:9)
    at /Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:282:63
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  status: 404,
  code: 20404,
  moreInfo: 'https://www.twilio.com/docs/errors/20404',
  details: undefined
} Promise {
  <rejected> RestException [Error]: The requested resource /Services/ISe0ef118171da46b9bd8ef1d33c82349e/Conversations/CHc8c5b974343a4546bb022e511885b6f1/Messages was not found
      at MessagePage.processResponse (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:135:19)
      at new Page (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/base/Page.js:17:28)
      at new MessagePage (/Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:315:9)
      at /Users/mimu/dev/summer-health/tmp/scripts/node_modules/twilio/lib/rest/conversations/v1/service/conversation/message.js:282:63
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    status: 404,
    code: 20404,
    moreInfo: 'https://www.twilio.com/docs/errors/20404',
    details: undefined
  }
}
```

### Technical details:
* twilio-node version: 4.14.0
* node version: 18.14.1

**Comment by jbzd** [comment]
We are experiencing this issue as well on the same library and node versions. Please advise - this is causing significant issues in our application,

**Comment by sbansla** [comment]
I am able to reproduce this issue.

**Comment by sbansla** [comment]
Internal ticket has been created, we are working actively working on it.

**Comment by sbansla** [comment]
https://github.com/twilio/twilio-node/blob/main/src/rest/conversations/v1/conversation/message.ts#L803
Above code snippet have not handled exception raised from:
https://github.com/twilio/twilio-node/blob/main/src/base/Page.ts#L226

--- We are checking our generator code, can this issue occur for all apis.

**Comment by dbburgess** [comment]
I can confirm this also happens for me for other APIs. Saw hundreds of these today, unfortunately:

```
There was an uncaught error: The requested resource /2010-04-01/Accounts/[redacted]/Calls/[redacted]/Events.json was not found
```

The code for this is simply:
```ts
try {
  const currentCall = await twilioClient.calls(CallSid).fetch();
  const currentCallEvents = await currentCall.events().list();
  // ...trimmed for brevity...
} catch (error) {
  logger.error("Error fetching call events", error);
}
```

**Comment by sbansla** [comment]
Hi @dbburgess,
Fix has been released, let us know if this works for you.

**Comment by dbburgess** [comment]
@sbansla Thank you, I'll upgrade and test it out.

CC: @mimu0 @jbzd

**Comment by abiodunooni** [comment]
@sbansla This still happens on the node SDK version 4.15.0

**Comment by abiodunooni** [comment]
@sbansla please check out this code block

`return new Promise((resolve, reject) => {
      pResolve = resolve;
      pReject = reject;
      fetchNextPage(this.page.bind(this, Object.assign(params, limits)));
    });`

if an error occurs in the fetchNextPage function, there's no catch block to handle it. I think this is where the unhandledRejection is still coming from.

`return new Promise((resolve, reject) => {
      pResolve = resolve;
      pReject = reject;
      fetchNextPage(this.page.bind(this, Object.assign(params, limits))).catch((error) => {
       reject(error);
     });
    });`

The code above should fix it

**Comment by abiodunooni** [comment]
@sbansla looking at the merged PR for this fix, you missed a catch block on line 346

please check out this code block

```javascript
return new Promise((resolve, reject) => { 
pResolve = resolve; 
pReject = reject; 
fetchNextPage(this.page.bind(this, Object.assign(params, limits))); 
});
``` 

if an error occurs in the fetchNextPage function, there's no catch block to handle it. I think this is where the unhandledRejection is still coming from.

```javascript
return new Promise((resolve, reject) => {
 pResolve = resolve;
 pReject = reject; 
  fetchNextPage(this.page.bind(this, Object.assign(params, limits))).catch((error) => { reject(error); 
   }); 
});
``` 

The code above should fix it

**Comment by abiodunooni** [comment]
@sbansla follow up to this issue.
I did some further digging and used the twilio API directly, without using the node SDK, and the error still occurs.

I don't think the issue is with the SDK but the API itself. most like there's a missing catch block that should be wrapped around the  `https://verify.twilio.com/v2/Services/VAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/Verifications"` API logic.

Please can you check this

**Comment by tiwarishubham635** [comment]
Closing this issue as no feedback was received in last 30 days
